### ISSUE TITLE
Information on using ghcjs missing, as well as releases.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [fpco/stackage-content#19]
From the stackage.org front-page, it is very hard to understand how to use ghcjs.

It is possible now to do cross-platform haskell development targeting iOS, Android, and Web using one code base as demonstrated in this project using nix:

https://github.com/jyrimatti/hseverywhere

It needs to be easier to start doing this using ghcjs.  Most of the examples that exist don't use stack, but rather use cabal. Even though no snapshot or lts is used for ghcjs, some information about which lts works with which ghcjs release, and support for the releases that actually exist at https://s3.amazonaws.com/ghcjs/ should be built-in.

So this issue is about:
1. Adding information about how to use ghcjs on the front page.  What are the limitations and what is the latest "probably working" lts/nightly/ghcjs combination.
2. Add all ghcjs releases to the default stack setup.

**Comment by mgsloan** [comment]
> 2. Add all ghcjs releases to the default stack setup.

We've been waiting for an official release of [ghcjs](https://github.com/ghcjs/ghcjs/issues/481).  All of the existing releases have just been someone taking master and labeling it with a version that has a date in it.  Since "old-base", 0.1.0, is a stable version, it seemed like a reasonable thing to put in setup-info.

Perhaps we should just go ahead and do that, though, and add some of these ghcjs snapshots to setup-info.

> 1. Adding information about how to use ghcjs on the front page. What are the limitations and what is the latest "probably working" lts/nightly/ghcjs combination.

I'm not sure if that info belongs on the stackage page.  We do have info in the stack docs http://docs.haskellstack.org/en/stable/ghcjs/

**Comment by alexanderkjeldaas** [comment]
The front page includes this text: "NOTE: Requires GHC 7.10. For GHC 7.8, please change the URL to https://www.stackage.org/lts-2/cabal.config".

It could indicate that ghcjs is not supported.  The front page should inform the user what stackage can be used for, and by omitting ghcjs the user gets the wrong impression.
